"""create user account table

Revision ID: 55e5b0d0f880
Revises: f4feb787bc44
Create Date: 2026-06-28 17:10:24.805830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e5b0d0f880'
down_revision: Union[str, Sequence[str], None] = 'f4feb787bc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'customer'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('tech_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tech_id'], ['technician.tech_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name='user_account_pkey'),
    sa.UniqueConstraint('email', name='user_account_email_key'),
    sa.UniqueConstraint('username', name='user_account_username_key')
    )
    op.drop_table('part_instance_credit_memos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_instance_credit_memos',
    sa.Column('credit_memo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('credit_memo_id', name=op.f('part_instance_credit_memos_pkey'))
    )
    op.drop_table('user_account')
    # ### end Alembic commands ###
