"""Add dynamic diagnostic templates and finding fields

Revision ID: 13a8e2972faa
Revises: 55e5b0d0f880
Create Date: 2026-07-21 21:24:25.445228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a8e2972faa'
down_revision: Union[str, Sequence[str], None] = '55e5b0d0f880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_template',
    sa.Column('template_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('template_id', name='diagnostic_template_pkey')
    )
    op.create_table('diagnostic_template_item',
    sa.Column('item_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['diagnostic_template.template_id'], name='diagnostic_template_item_template_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name='diagnostic_template_item_pkey')
    )
    op.create_index('idx_diagnostic_template_item_template', 'diagnostic_template_item', ['template_id'], unique=False)
    op.add_column('diagnostic_finding', sa.Column('recommended_service', sa.String(length=500), nullable=True))
    op.add_column('diagnostic_finding', sa.Column('is_critical', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostic_finding', 'is_critical')
    op.drop_column('diagnostic_finding', 'recommended_service')
    op.drop_index('idx_diagnostic_template_item_template', table_name='diagnostic_template_item')
    op.drop_table('diagnostic_template_item')
    op.drop_table('diagnostic_template')
    # ### end Alembic commands ###
