"""add warranty_required

Revision ID: c285749d2193
Revises: 13a8e2972faa
Create Date: 2026-07-22 15:43:04.055734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c285749d2193'
down_revision: Union[str, Sequence[str], None] = '13a8e2972faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('preferred_time', sa.String(length=10), nullable=True))
    op.add_column('line_item', sa.Column('is_complimentary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('line_item', sa.Column('warranty_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('part', sa.Column('warranty_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('visit', sa.Column('walk_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('work_order', sa.Column('diagnostic_bypassed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('work_order', sa.Column('bypass_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'bypass_reason')
    op.drop_column('work_order', 'diagnostic_bypassed')
    op.drop_column('visit', 'walk_in')
    op.drop_column('part', 'warranty_required')
    op.drop_column('line_item', 'warranty_required')
    op.drop_column('line_item', 'is_complimentary')
    op.drop_column('appointment', 'preferred_time')
    # ### end Alembic commands ###
